language: java
sudo: false
cache:
  directories:
  - "${HOME}/.m2"
services:
  - docker
env:
  global:
  - NODE_ENV=CI
  - CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1;
script: mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
- echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee
  -a /etc/apt/sources.list.d/google-cloud-sdk.list;
- curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- sudo apt-get update && sudo apt-get install google-cloud-sdk
- gcloud --quiet version
- sudo apt-get install kubectl
- openssl aes-256-cbc -K $encrypted_06d29828bf05_key -iv $encrypted_06d29828bf05_iv
  -in server/src/main/ops/auth.json.enc -out server/src/main/ops/auth.json -d

deploy:
  - provider: script
    script: bash server/src/main/ops/deploy.sh
    skip_cleanup: true
    on:
      branch: master
      tags: true
